server:
  port: 13124

#spring:
#  application:
#    name: nacos-client-1
#  datasource:
#    url: jdbc:mysql://192.168.201.16:3306/callcenter?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
#    username: callcenter
#    password: callcenter
#    driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  zipkin:
#    base-url: http://localhost:9411/
#file:
#  uploadDir: E:/test
spring:
  servlet:
    multipart:
      enabled: true
      # 单个文件最大
      max-file-size: 1MB
      # 单次请求最大
      max-request-size: 10MB
      # 上传文件临时存放位置
      location: E:/temp
feign:
  hystrix:
    enabled: true
  client:
    # feign 默认配置为 连接超时 10秒，读超时 60秒
    # 如果开启 ribbon，并且配置了feign的超时时间，那么以feign的为准。否则以ribbon为准，ribbon默认连接超时、读超时都为1秒
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

# ribbon 默认为1秒
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

hystrix:
  command:
    # hystrix 默认线程超时为 1 秒
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
